React 16.3 and Demo
civicsource/react-inline-confirm pull request #6
Opened 2018-04-04 19:18 UTC by cdakin1

Fixes [CS-16356](https://jira.archoninfosys.com:8181/browse/CS-16356?filter=-1)
Related: [Civicsource #1657](https://github.com/civicsource/civicsource/pull/1657)

Issue: In preparation for react 17, various lifecycle methods needed to be removed.

Fix: Move contents of componentWillReceiveProps and componentWillMount to componentDidUpdate.

Also adds an example that can be run locally.

2018-04-04 19:19 UTC, chrisdakin commented
@chadly I've never setup webpack config stuff so there might be (read: is) a better way to run the example locally (like with hot reload or whatever magic stuff), not sure exactly what you want that setup to look like though.

Also not sure if we need the packagelock commited, or if we want to go with npm vs yarn, etc.

2018-04-04 19:37 UTC, mdarens submitted a review, later dismissed

2018-04-04 19:40 UTC, chadly requested changes
Use yarn & webpack v4

2018-04-04 19:40 UTC, chadly commented on package.json
> +    "build": "webpack --progress --bail",
We don't need this `build` script.

2018-04-04 21:01 UTC, chadly requested changes

2018-04-04 21:01 UTC, chadly commented on package.json
> +    "react": "^16.3"
Does the ^ allow lower than 16.3? I think it should be `>=16.3 < 18`.

2018-04-04 21:29 UTC, chadly requested changes

2018-04-04 21:29 UTC, chadly commented on package.json
> +    "react-dom": "^>=16.3 < 18"
Don't add `react`/`react-dom` as dependencies. We want to keep them as `peerDependencies` to let consuming apps not accidentally pull in multiple react versions.

To make the demo work, move these to `devDependencies`.

2018-04-04 21:43 UTC, mdarens submitted a review, later dismissed

2018-04-04 21:44 UTC, chadly requested changes

2018-04-04 21:44 UTC, chadly commented on package.json
> +    "react-dom": "^>=16.3 < 18",
For `devDependencies`, you can just use the specific version: `^16.3.0`. The range is for the consuming app.

2018-04-09 16:42 UTC, chadly requested changes

2018-04-09 16:42 UTC, chadly commented on package.json
> +    "react": "^>=16.3 < 18"
The `^` is not valid methinks

2018-04-10 21:37 UTC, chadly approved these changes

2018-04-10 21:38 UTC, merged

2018-04-10 21:42 UTC, chadly commented
Published as [`v3.0.0`](https://github.com/civicsource/react-inline-confirm/releases/tag/v3.0.0)